### PR TITLE
Rename to kafka connect

### PR DESCRIPTION
**Pull request by Ishiihara**
@ewencp @miguno rename to Kafka connect.

### CODE REVIEW

**Comment by miguno** [comment]
In general LGTM.  Tests passed.

One question (for the sake of completeness):  I did a quick check for outdated maven dependencies.
```
$ mvn versions:display-dependency-updates
[...]
[INFO] The following dependencies in Dependencies have newer versions:
[INFO]   org.apache.hadoop:hadoop-client ....................... 2.6.0 -> 2.7.1
[INFO]   org.apache.hadoop:hadoop-minicluster .................. 2.6.0 -> 2.7.1
[INFO]   org.apache.parquet:parquet-avro ....................... 1.7.0 -> 1.8.1
[INFO]   org.apache.parquet:parquet-column ..................... 1.7.0 -> 1.8.1
```

Should we bump any of these outdated versions (or not)?  I assume that the Hadoop version we want to build against is also influenced by which Hadoop distributions we want to be compatible with.  Again, just asking this for completeness' sake.

**Comment by ewencp** [comment]
@Ishiihara The changes look good, but there are still a few remaining references to Copycat:

```
$ git grep -i copycat
README.md:# copycat-hdfs
README.md:Copycat HDFS connector
src/assembly/development.xml:            <outputDirectory>share/java/copycat-hdfs/</outputDirectory>
src/assembly/package.xml:            <outputDirectory>share/doc/copycat-hdfs/</outputDirectory>
src/assembly/package.xml:            <outputDirectory>etc/copycat-hdfs</outputDirectory>
src/assembly/package.xml:            <outputDirectory>share/java/copycat-hdfs</outputDirectory>
src/assembly/package.xml:                <exclude>io.confluent:copycat</exclude>
src/assembly/standalone.xml:    <!-- Assembles a packaged jar that includes all dependencies. This still requires the copycat
src/assembly/standalone.xml:     runtime, but allows running copycat with a connector plugin using only a couple of jars. -->
src/test/java/io/confluent/connect/hdfs/HdfsSinkConnectorTestBase.java:     * Get offsets that the SinkTask has submitted to be reset. Used by the Copycat framework.
src/test/java/io/confluent/connect/hdfs/HdfsSinkConnectorTestBase.java:     * Get the timeout in milliseconds set by SinkTasks. Used by the Copycat framework.
```

**Comment by Ishiihara** [comment]
@miguno Thank you for the fix. I will leave the Hadoop versions for now and make necessary modifications if issues come up during system tests.

**Comment by Ishiihara** [comment]
@ewencp Made the necessary changes.

**Comment by ewencp** [comment]
@Ishiihara LGTM

**Pull request merged**
